### PR TITLE
Reduce utils, additional Sequence Operators

### PR DESCRIPTION
**Pull request by hwayne**
A lot of the stuff I wanted to add is already in the modules, which is pretty cool. So here's a few extra bits: first, some extra sequence constructors. Second, a "reduce" module for folding operators over sets and sequences. This is to make writing things like `sum` more accessible to people.

I tried to follow the commenting conventions of the other modules here. Note that I don't have tests just yet but I'm happy to add them.

### CODE REVIEW

**Comment by lemmy** [comment]
What about renaming `Reduce` to `FiniteSetsExt`?

**Comment by hwayne** [comment]
I don't see a problem with renaming. One question: we'd then want to move ` ReduceSeq` to ` SequencesExt.tla`, but it depends on `ReduceSet`. Are these kinds of cross module operators okay or should I copy it over as a local operator?

**Comment by lemmy** [comment]
A dependency `SequencesExt` -> `FiniteSetsExt` shouldn't be a problem because they are in the same repository.   Alternatively, could copy the body of `ReduceSet` to `ReduceSeq` along with an implementation note?

In the long run, we have to be careful though to not create a small number of uber-modules whose operator definitions collide with what user have in spec (e.g. `Contains` in `SequencesExt` might turn out too generic).

**Comment by lemmy** [comment]
b3029e0ce73d58f09c3a3e82fa3a888acb23d7de has the changes discussed above.

**Pull request closed without merging**
