### PR TITLE
WIP: Improve JSON serialization

### PR DESCRIPTION
**Pull request by lvanengelen**
- Export sets and sequences as JSON arrays, records as JSON objects
- Handle nested JSON structures
- Handle more types of TLA+ values

### CODE REVIEW

**Comment by lemmy** [comment]
Since @kuujo is working on related functionality, let's coordinate to avoid/minimize merge conflicts.

**Comment by kuujo** [comment]
I will open a PR today and we can decide what to do with the two. But FWIW, while this PR serialized to JSON without any additional dependencies, parsing is much more difficult so we’re going to need a JSON library (I’m currently using Jackson) for input operators anyways. Once that requirement has been introduced, the JSON library might as well be used for serialization as well.

**Comment by kuujo** [comment]
@lvanengelen I more or less merged your more thorough types and tests into #9, so I think this PR should be mostly obsolete. But take a look and see if I missed anything.

**Comment by lemmy** [comment]
@lvanengelen Do the operators merged in https://github.com/tlaplus/CommunityModules/pull/9 work for you?

**Comment by lvanengelen** [comment]
Yes, I think they will. While going over the changes I noticed a duplicate test case (https://github.com/tlaplus/CommunityModules/blob/master/tests/JsonTests.tla#L7).

**Comment by lemmy** [comment]
https://github.com/tlaplus/CommunityModules/commit/9031f9aab3152b120b445ceda4baf20aa1dd1141

**Pull request closed without merging**
